### ISSUE TITLE
What is the hack?

### ISSUE THREAD

**Issue by bilogic** [hablutzel1/phpcmstimestamper#1]
https://github.com/hablutzel1/phpcmstimestamper/blob/f1688a09d6619219a90527db5b78e06571620f91/src/CmsTimestamper.php#L9-L15

I tried creating the timestamp with https://github.com/FGrosse/PHPASN1 but was unsuccessful.
The code above indicated it is some kind of hack. What is the hack that is being achieved here? Thank you.

**Comment by hablutzel1** [comment]
@bilogic , are you trying to add a timestamp to an existing CMS signature? Now, I don't remember this project very well right now, but, did you try executing https://github.com/hablutzel1/phpcmstimestamper/blob/master/demo.php ? If it works for you, you could debug and understand how does the `CmsTimestamper` class work.

**Comment by bilogic** [comment]
@hablutzel1 yes, I'm trying to add timestamp. I managed to sign a PDF, but it can only use a test PFX. If I use a paid PFX, the PDF end up cannot open.

**Comment by bilogic** [comment]
@hablutzel1 I do understand how the class work, what I don't understand is why some values are hardcoded.. and why you call `importedValueTypeDeclaration` a "hack".

**Comment by hablutzel1** [comment]
The hardcoded values correspond to ASN.1 tag numbers as you can see below (last capture obtained with ASN.1 Editor):

![image](https://user-images.githubusercontent.com/230942/193647068-01ee09d1-550c-4bed-87d2-44625af86810.png)

![image](https://user-images.githubusercontent.com/230942/193647020-ed94e0be-6a6b-47a5-bb9c-072ffe29b13a.png)

Now, I don't remember exactly why I called `importedValueTypeDeclaration` a hack, but my guess is that it was the only way I found to set arbitrary ASN.1 tag numbers to those elements, even when the code inside that function doesn't look intended for that purpose.

When you use the paid PFX the doesn't open at all or only the signature doesn't validate?

**Comment by bilogic** [comment]
What software do you use to analyze/get those images?
The paid PFX can be loaded as certs, but the PDF reader cannot open it, almost like it is corrupted

**Comment by hablutzel1** [comment]
> What software do you use to analyze/get those images?

ASN.1 Editor. If you use Windows you could get it from https://community.chocolatey.org/packages/asn1editor.

> The paid PFX can be loaded as certs, but the PDF reader cannot open it, almost like it is corrupted

Open your PDF in a regular text editor and/or use iText 7 RUPS (https://github.com/itext/i7j-rups) to inspect its structure and see if you find something abnormal around the CMS related dictionaries.

**Comment by bilogic** [comment]
Cool! Thank you so much

**Comment by bilogic** [comment]
RUPS can't open the corrupted file 😂

**Comment by hablutzel1** [comment]
@bilogic , study a little about PDF structure and then open the PDF in a good text editor. It should allow you to spot the problematic section.
